modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="coffee"
version="4"
displayName="Coffee+"
credits="Thanks to MCreator for making this mod possible."
displayURL="https://www.curseforge.com/minecraft/mc-mods/coffee-plus"
authors="hyphen"
description='''
Adds coffee to Minecraft
'''

[[dependencies.coffee]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




