modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="coffee"
version="0.0.7"
displayName="Coffee+"
credits="Thanks to MCreator for making this mod possible."
displayURL="https://www.curseforge.com/minecraft/mc-mods/coffee-plus"
logoFile="logo.png"
authors="hyphen"
description='''
Grow, harvest, and drink your very own coffee.
'''

[[dependencies.coffee]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




