modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="coffee"
version="0.0.9"
displayName="Coffee+"
credits="Thanks to MCreator for making this mod possible, and to everyone who has downloaded it for their continued support."
displayURL="https://ko-fi.com/hyphengg"
logoFile="logo.png"
authors="hyphengg"
description="Coffee Plus adds coffee to Minecraft, the way coffee should be done. "

[[dependencies.coffee]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.coffee]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0]"
    ordering="NONE"
    side="BOTH"



